config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/alert' => 'buttons#alert'
  post '/alert' => 'buttons#alert'
  put 'alert' => 'buttons#alert'

  post '/newkey' => 'misc_pages#newkey'
  get '/newdevice' => 'misc_pages#newdevice'
  resources :buttons

  root to: 'misc_pages#index'

end

app/models/apikey.rb
class Apikey < ActiveRecord::Base
  belongs_to :user
  has_many :buttons
end

app/models/button.rb
class Button < ActiveRecord::Base
  belongs_to :apikey
  has_many :buttoncontacts
end

app/models/buttoncontact.rb
class Buttoncontact < ActiveRecord::Base
  belongs_to :button
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :apikeys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  alias_method :devise_current_user, :current_user
  before_action :auth_needed?#:authenticate_user!

  private

  def current_user
    return devise_current_user if request.format != :json
    return @_current_user if @_current_user
    token = request.headers["HTTP_AUTH_TOKEN"]
    key = Apikey.where(token: token).first!
    @_current_user = key.user
  end

  def auth_needed?
    authenticate_user! if request.format != :json
  end

end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController

  def index
    @buttons = current_user.apikeys.first.buttons
    respond_to do |format|
      format.html
      format.json
    end
  end

  def alert
    
    account_sid = ENV["twillio_sid"]
    account_token = ENV["twillio_token"]
    
    # set up a client to talk to the Twilio REST API
    @client = Twilio::REST::Client.new account_sid, account_token

    # alternatively, you can preconfigure the client like so
    Twilio.configure do |config|
      config.account_sid = account_sid
      config.auth_token = account_token
    end

    # and then you can create a new client without parameters
    @client = Twilio::REST::Client.new
    @client2 = Twilio::REST::Client.new    
    
    @client.messages.create(
      from: '+16784981022',
      to: '+14049989321',
      #to: ['+14044068958','+14049989321'],
      body: 'Hey there!'
    )
   
    @client2.messages.create(
      from: '+16784981022',
      to: '+14044068958',
      body: 'Hey there 2!'
    )

    AlertMailer.send_alert(1).deliver
  end

end

app/controllers/misc_pages_controller.rb
class MiscPagesController < ApplicationController
  def index
    if current_user.apikeys.first == nil
      render :newkey
    else
      @key = current_user.apikeys.first
      @buttons = @key.buttons
    end
  end

  def newkey
    @device = params["device"]
    @key = current_user.apikeys.new
    @key.name = @device
    @key.token = @device.gsub(/\s+/, "").reverse
    if @key.save!
      redirect_to :action => 'newdevice'      
      #redirect_to root_path 
    end
  end

  def newdevice
    @key = current_user.apikeys.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/misc_pages_helper.rb
module MiscPagesHelper
end

app/views/buttons/index.html.haml
.h1 Hello

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Emergency"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Emergency
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Log Out", destroy_user_session_path, method: :delete 

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/misc_pages/index.html.haml
%h3
  = "Settings for device: #{@key.name}"

%table.table.table-striped
  %tbody
    %tr
      %td 
        = check_box_tag 'default1'
        -#= label_tag 'default1'
      %td
        = check_box_tag 'default2'
      %td
        = check_box_tag 'default3'
      %td
        = check_box_tag 'default4'
    %tr
      %td 
        = image_tag "emergency.png"
      %td
        = image_tag "stranger.png"
      %td
        = image_tag "fallen.png"
      %td
        = image_tag "pick.png"
- if @buttons.size ==  0
  = form_tag buttons_path, :method => :post do
    %div#b1{style:"display:none"}
      %p
      %h2#bn1 Emergency
      %table.table.table-striped#t1
        %thead
          %tr
            %th 
              %button.btn.btn-mini.btn-primary#add_row1{type:"button"} + 
            %th Email
            %th SMS
          %tbody
            %tr
              %td 1
              %td
                = text_field_tag 'email'
              %td
                = text_field_tag 'sms'
      %button.btn.btn-mini.btn-primary#save1{type:"button"} Save
    %div#b2{style:"display:none"}
      %p
      %h2#bn2 Stranger Danger 
      %table.table.table-striped#t2
        %thead
          %tr
            %th 
              %button.btn.btn-mini.btn-primary#add_row2{type:"button"} + 
            %th Email
            %th SMS
          %tbody
            %tr
              %td 1
              %td
                = text_field_tag 'email'
              %td
                = text_field_tag 'sms'
      %button.btn.btn-mini.btn-primary#save2{type:"button"} Save  
    %div#b3{style:"display:none"}
      %p
      %h2#bn3 I've Fallen
      %table.table.table-striped#t3
        %thead
          %tr
            %th 
              %button.btn.btn-mini.btn-primary#add_row3{type:"button"} + 
            %th Email
            %th SMS
          %tbody
            %tr
              %td 1
              %td
                = text_field_tag 'email'
              %td
                = text_field_tag 'sms'
      %button.btn.btn-mini.btn-primary#save3{type:"button"} Save
    %div#b4{style:"display:none"}
      %p
      %h2#bn4 Come Pick Me Up 
      %table.table.table-striped#t4
        %thead
          %tr
            %th 
              %button.btn.btn-mini.btn-primary#add_row4{type:"button"} + 
            %th Email
            %th SMS
          %tbody
            %tr
              %td 1
              %td
                = text_field_tag 'email'
              %td
                = text_field_tag 'sms'
      %button.btn.btn-mini.btn-primary#save4{type:"button"} Save      
- else
  %p Existing Buttons
:javascript
  $(function() {

    $('#default1').bind('change', function () {
      toggle_d(1);
    });
    
    $('#default2').bind('change', function () {
      toggle_d(2);
    });
    
    $('#default3').bind('change', function () {
      toggle_d(3);
    });
    
    $('#default4').bind('change', function () {
      toggle_d(4);
    });
    
    var toggle_d = function(num){
      if ($('#default'+num).is(':checked'))
        $('#b'+num).show();
      else
        $('#b'+num).hide();
    }
    
    var new_row = function(num) {
      $("#b"+num+">table>tbody>tr:first-child").clone().appendTo("#t"+num)
      var next_num = $("#b"+num+">table>tbody>tr").length
      $("#b"+num+">table>tbody>tr:last-child>td:first-child").text(next_num)
    }
    
    $('#add_row1').click(function(e) {
      new_row(1);
    });

    $('#add_row2').click(function(e) {
      new_row(2);
    });

    $('#add_row3').click(function(e) {
      new_row(3);
    });
    
    $('#add_row4').click(function(e) {
      new_row(4);
    });

  });

app/views/misc_pages/newdevice.html.haml
%div{align:"center"}
  %h3 Put the following code in your iPhone when prompted: 
  %h1{style: "color:#77d624; font-size:450%",}
    = @key.token
  %p
    = image_tag 'iphone1.png', size: '300x480'

  %p
  %p
    = link_to 'Continue', root_path, {class: "btn btn-primary"}

app/views/misc_pages/newkey.html.haml
%p Hello!
%p
%p Before you can continue, please tell us then name fo the device you will be configuring.  If you don't know, just make something up.  Something like "john boy's iphone" or similar will be just fine.
= form_tag '/newkey', method: :post do
  %p
    = text_field_tag 'device'
  %p
    = submit_tag 'Continue', class: "btn btn-primary"